name: Docker Image Elasticsearch
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    paths:
      - elasticsearch/**
      - .github/workflows/elasticsearch.yml

jobs:
  elasticsearch:
    name: Elasticsearch
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "5"
          - "6"
          - "7.6"
          - "7.7"
          - "7.9"
          - "7.10"
          - "7.12"
          - "7.13"
          - "7.14"
          - "7.15"
          - "7.16"
          - "7.17"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
          - "8.6"
          - "8.7"
          - "8.8"
          - "8.9"
          - "8.10"
          - "8.11"
          - "8.12"
          - "8.13"
          - "8.14"
          - "8.15"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Set build-args
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          ES_VERSION=$(
            docker run --rm gcr.io/go-containerregistry/crane:v0.8.0 ls docker.elastic.co/elasticsearch/elasticsearch \
            | egrep "^${ESCAPED_VERSION}\.[0-9]+(\.[0-9]+)?\$" | sort -Vr | head -n1
          )
          echo "ES_VERSION=${ES_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - uses: docker/build-push-action@v3
        with:
          context: elasticsearch
          platforms: linux/amd64,linux/arm64
          build-args: ES_VERSION=${{ env.ES_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/elasticsearch:${{ matrix.version }}, wardenenv/elasticsearch:${{matrix.version}}
